namespace Graduation.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class InitialCreate : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Students",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        StudentNumber = c.String(),
                        Pwd = c.String(),
                        ImgPath = c.String(),
                        StudentType = c.String(),
                        Name = c.String(),
                        Sex = c.String(),
                        SexCode = c.String(),
                        BirthTime = c.String(),
                        SFstudentCode = c.String(),
                        YKSH = c.String(),
                        KSH = c.String(),
                        ChangeCode = c.String(),
                        School = c.String(),
                        SchoolCode = c.String(),
                        SchoolBeCode = c.String(),
                        SchoolAddCode = c.String(),
                        Academy = c.String(),
                        Department = c.String(),
                        Major = c.String(),
                        MajorCode = c.String(),
                        MajorDirection = c.String(),
                        Class = c.String(),
                        TeachingClass = c.String(),
                        Nation = c.String(),
                        NationCode = c.String(),
                        IDNumber = c.String(),
                        Health = c.String(nullable: false),
                        PoliticalStatus = c.String(nullable: false),
                        PoliticalStatusCode = c.String(),
                        ClassTeacher = c.String(nullable: false),
                        TelNumber = c.String(nullable: false),
                        Email = c.String(nullable: false),
                        QQ = c.String(nullable: false),
                        Dormitory = c.String(nullable: false),
                        RoomNumber = c.String(nullable: false),
                        IsResidenceToSch = c.String(nullable: false),
                        IsMargery = c.String(nullable: false),
                        IsArchivesToSch = c.String(nullable: false),
                        PoliceBefore = c.String(nullable: false),
                        IsChangeMaj = c.String(nullable: false),
                        BeforeMajor = c.String(),
                        IsOnlyChild = c.String(nullable: false),
                        DiffLevel = c.String(nullable: false),
                        DiffLevelCode = c.String(),
                        FDiffLevel = c.String(nullable: false),
                        IsChangeOrigin = c.String(nullable: false),
                        Origin = c.String(nullable: false),
                        OriginProvince = c.String(nullable: false),
                        OriginCity = c.String(nullable: false),
                        OriginCounty = c.String(nullable: false),
                        OriginCode = c.String(),
                        ResLocationType = c.String(nullable: false),
                        ResLocation = c.String(nullable: false),
                        ResProvince = c.String(nullable: false),
                        ResCity = c.String(nullable: false),
                        ResCounty = c.String(nullable: false),
                        ResLocationCode = c.String(),
                        ResType = c.String(nullable: false),
                        Post = c.String(nullable: false),
                        FamilyTel = c.String(nullable: false),
                        OtherTel = c.String(nullable: false),
                        CommCode = c.String(nullable: false),
                        CommAddress = c.String(nullable: false),
                        FamilyZipCode = c.String(nullable: false),
                        FamilyLocation = c.String(nullable: false),
                        FatherName = c.String(nullable: false),
                        FatherWorkUnit = c.String(nullable: false),
                        MotherName = c.String(nullable: false),
                        MotherWorkUnit = c.String(nullable: false),
                        BaseNote = c.String(nullable: false),
                        IsBaseChecked = c.String(),
                        LengthOfSch = c.String(),
                        Education = c.String(),
                        EducationCode = c.String(),
                        TrainType = c.String(),
                        TrainTypeCode = c.String(),
                        Weituo = c.String(),
                        EntranceYear = c.String(),
                        EntranceTime = c.String(),
                        GraduationTime = c.String(),
                        NM = c.String(),
                        NumberN = c.String(),
                        NumberM = c.String(),
                        RankType = c.String(),
                        PostAtSch = c.String(),
                        FristYearPrize = c.String(),
                        SecondYearPrize = c.String(),
                        ThirdYearPrize = c.String(),
                        BriefPrize = c.String(),
                        EnglishLevel = c.String(),
                        LevelFour = c.String(),
                        LevelSix = c.String(),
                        ComputerLevel = c.String(),
                        ApplNote = c.String(),
                        StudyTest = c.String(),
                        MoralTest = c.String(),
                        ScienceTest = c.String(),
                        ActTest = c.String(),
                        CultureTest = c.String(),
                        HealthTest = c.String(),
                        TotalTest = c.String(),
                        IsQiuChecked = c.String(),
                        EmploymentType = c.String(),
                        AgreementID = c.String(),
                        CompanyName = c.String(),
                        ComBelongGroup = c.String(),
                        CompanyCode = c.String(),
                        ComBelongDep = c.String(),
                        ComBelongDepCode = c.String(),
                        ComIndustry = c.String(),
                        ComIndustryCode = c.String(),
                        JobTitle = c.String(),
                        JobTitleCode = c.String(),
                        SCompanyName = c.String(),
                        ComLocation = c.String(),
                        ComProvince = c.String(),
                        ComCity = c.String(),
                        ComCounty = c.String(),
                        ComType = c.String(),
                        ComTypeCode = c.String(),
                        Contacts = c.String(),
                        ContactsCode = c.String(),
                        ConCommAddress = c.String(),
                        ConPost = c.String(),
                        ConTel = c.String(),
                        ResChangedAdd = c.String(),
                        FileChangedAdd = c.String(),
                        FileZipCode = c.String(),
                        IsMajorFit = c.String(),
                        Note = c.String(),
                        UpType = c.String(),
                        UPSchool = c.String(),
                        UpMajor = c.String(),
                        OutSchool = c.String(),
                        OutMajor = c.String(),
                        OutCountry = c.String(),
                        SignTimeQ = c.String(),
                        CompanyNameQ = c.String(),
                        ComBelongGroupQ = c.String(),
                        ComBelongDepQ = c.String(),
                        ComBelongDepCodeQ = c.String(),
                        ComTypeQ = c.String(),
                        CompanyAddressQ = c.String(),
                        CompanyConnQ = c.String(),
                        CompanyTelQ = c.String(),
                        PerTelTypeQ = c.String(),
                        SignTypeQ = c.String(),
                        AgreementIDQ = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.Students");
        }
    }
}
